package rmit.saintgiong.discoveryservice.searchprofile.mapper;

import lombok.extern.slf4j.Slf4j;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Named;
import rmit.saintgiong.discoveryapi.internal.dto.CreateSearchProfileRequestDto;
import rmit.saintgiong.discoveryapi.internal.dto.SearchProfileResponseDto;
import rmit.saintgiong.discoveryservice.common.degree.type.DegreeType;
import rmit.saintgiong.discoveryservice.common.degree.type.EmploymentTypeEnum;
import rmit.saintgiong.discoveryservice.common.exception.InvalidEnumValueException;
import rmit.saintgiong.discoveryservice.searchprofile.entity.SearchProfileEntity;
import rmit.saintgiong.discoveryservice.searchprofile.entity.SearchProfile_SkillTagEntity;

import java.util.BitSet;
import java.util.Collections;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;

@Slf4j
@Mapper(componentModel = "spring")
public abstract class SearchProfileMapper {

    @Mapping(target = "employmentTypes", source = "employmentType", qualifiedByName = "mapBitSetToStrings")
    @Mapping(target = "skillTagIds", source = "skillTags", qualifiedByName = "mapSkillTagsToIds")
    public abstract SearchProfileResponseDto entityToResponseDto(SearchProfileEntity savedProfile);

    @Named("mapBitSetToStrings")
    protected Set<String> mapBitSetToStrings(BitSet bitSet) {
        if (bitSet == null || bitSet.isEmpty()) {
            return Collections.emptySet();
        }

        return bitSet.stream()
                .mapToObj(index -> {
                    // Find the Enum matching this index
                    for (EmploymentTypeEnum e : EmploymentTypeEnum.values()) {
                        if (e.getBitIndex() == index) {
                            return e.name();
                        }
                    }
                    return null;
                })
                .filter(Objects::nonNull)
                .collect(Collectors.toSet());
    }


    /**
     * Extracts the Integer tagId from the join entity.
     */
    @Named("mapSkillTagsToIds")
    protected Set<Integer> mapSkillTagsToIds(Set<SearchProfile_SkillTagEntity> skillTags) {
        if (skillTags == null) {
            return Collections.emptySet();
        }
        return skillTags.stream()
                .map(entity -> entity.getSkillTagId().getTagId())
                .collect(Collectors.toSet());
    }


    @Mapping(target = "profileId", ignore = true) // Generated by DB
    @Mapping(target = "skillTags", ignore = true) // Handled in Service
    @Mapping(target = "employmentType", source = "employmentTypes", qualifiedByName = "mapStringsToBitSet")
    @Mapping(target = "highestDegree", source = "highestDegree", qualifiedByName = "mapStringToDegreeType")
    public abstract SearchProfileEntity requestDtoToEntity(CreateSearchProfileRequestDto dto);

    @Named("mapStringToDegreeType")
    protected DegreeType mapStringToDegreeType(String degree) {
        if (degree == null || degree.isBlank()) {
            return null;
        }
        try {
            return DegreeType.valueOf(degree.toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new InvalidEnumValueException(
                    "degree type",
                    degree,
                    new String[]{"BACHELOR", "MASTER", "DOCTORATE"});
        }
    }

    @Named("mapStringsToBitSet")
    protected BitSet mapStringsToBitSet(Set<String> types) {
        if (types == null || types.isEmpty()) {
            return new BitSet();
        }
        BitSet bitSet = new BitSet();
        for (String type : types) {
            try {
                int index = EmploymentTypeEnum.getIndexByName(type);
                bitSet.set(index);
            } catch (IllegalArgumentException e) {
                throw new InvalidEnumValueException(
                        "employment type",
                        type,
                        new String[]{"FULL_TIME", "PART_TIME", "FRESHER", "INTERNSHIP", "CONTRACT"});
            }
        }
        return bitSet;
    }


}